spring:
  datasource:
    accounting:
      url: jdbc:mysql://accounting-service.ckdb8i72sy2s.rds.cn-north-1.amazonaws.com.cn:3306/accounting?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: welcome1
      filters: stat,wall
      driver-class-name: com.mysql.jdbc.Driver
    crs:
      url: jdbc:postgresql://staging-crs-prod.ckdb8i72sy2s.rds.cn-north-1.amazonaws.com.cn:5432/oyoprod
      username: uc0s0psnqc13qs
      password: admin12345
      filters: stat,wall
      driver-class-name: org.postgresql.Driver

  thymeleaf:
    # 这个是配置模板路径的，默认是templates
    prefix: classpath:/templates/
    suffix: .html
    # 模板的模式
    #spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    content-type: text/html
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  # 设置上传文件的最大值
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB    
    
server:
  port: 8001


logging:
  level:
    root: INFO
    com.oyo.accouting.mapper: DEBUG
    


      
    
