package com.oyo.accouting.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-08-02T14:29:33.880+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SAPWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SAPWebServiceSoap {

    @WebMethod(operationName = "JournalEntries", action = "http://tempuri.org/JournalEntries")
    @RequestWrapper(localName = "JournalEntries", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.JournalEntries")
    @ResponseWrapper(localName = "JournalEntriesResponse", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.JournalEntriesResponse")
    @WebResult(name = "JournalEntriesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String journalEntries(
        @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
        java.lang.String json
    );

    @WebMethod(operationName = "Invoices", action = "http://tempuri.org/Invoices")
    @RequestWrapper(localName = "Invoices", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.Invoices")
    @ResponseWrapper(localName = "InvoicesResponse", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.InvoicesResponse")
    @WebResult(name = "InvoicesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String invoices(
        @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
        java.lang.String json
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "BusinessPartners", action = "http://tempuri.org/BusinessPartners")
    @RequestWrapper(localName = "BusinessPartners", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.BusinessPartners")
    @ResponseWrapper(localName = "BusinessPartnersResponse", targetNamespace = "http://tempuri.org/", className = "com.oyo.accouting.webservice.BusinessPartnersResponse")
    @WebResult(name = "BusinessPartnersResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String businessPartners(
        @WebParam(name = "Json", targetNamespace = "http://tempuri.org/")
        java.lang.String json
    );
}
