package com.oyo.accouting.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-08-02T14:29:33.886+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "SAPWebService",
                  wsdlLocation = "http://localhost:8080/SAPWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class SAPWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SAPWebService");
    public final static QName SAPWebServiceSoap = new QName("http://tempuri.org/", "SAPWebServiceSoap");
    public final static QName SAPWebServiceSoap12 = new QName("http://tempuri.org/", "SAPWebServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SAPWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SAPWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SAPWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SAPWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SAPWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SAPWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SAPWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SAPWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SAPWebServiceSoap
     */
    @WebEndpoint(name = "SAPWebServiceSoap")
    public SAPWebServiceSoap getSAPWebServiceSoap() {
        return super.getPort(SAPWebServiceSoap, SAPWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPWebServiceSoap
     */
    @WebEndpoint(name = "SAPWebServiceSoap")
    public SAPWebServiceSoap getSAPWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(SAPWebServiceSoap, SAPWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SAPWebServiceSoap
     */
    @WebEndpoint(name = "SAPWebServiceSoap12")
    public SAPWebServiceSoap getSAPWebServiceSoap12() {
        return super.getPort(SAPWebServiceSoap12, SAPWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPWebServiceSoap
     */
    @WebEndpoint(name = "SAPWebServiceSoap12")
    public SAPWebServiceSoap getSAPWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(SAPWebServiceSoap12, SAPWebServiceSoap.class, features);
    }

}
